### ISSUE TITLE
Firefox 41.0.2 +  bug

### ISSUE THREAD

**Issue by saesaeru** [InstantBusinessNetwork/IBN#2]
Can't open IBN portal in new versions of Mozilla Firefox 41.0.2 +  (white screen and non stop refreshing after login)

**Comment by OlegoO** [comment]
Could you capture traffic using Fiddler (FiddlerCap )? 

To use:
1. Download Fiddler http://www.fiddler2.com/fiddler2/.
2. Open it.
3. Clear your browser cache.
4. Browse to your site. Visit the pages that are problematic and a contrasting non-problematic page if appropriate, for contrast.
5. Click File > Save > All Sessions....
6. Attach the resulting file in .saz format for Support.

**Comment by saesaeru** [comment]
Rename in to *.saz
![ibn-refresh-bug-firefox saz](https://cloud.githubusercontent.com/assets/7147646/10782445/7f37f09c-7d61-11e5-9a8c-fd85d4b87ce7.jpg)

**Comment by RaZLeN** [comment]
working only with firefox 40.0.3 and older
