### ISSUE TITLE
Забрать данные?

### ISSUE THREAD

**Issue by IvanBetev** [InstantBusinessNetwork/IBN#3]

**Comment by OlegoO** [comment]
Тут выложен только source код IBN проекта.
Дайте более подробную информацию о вашем портале.

**Comment by IvanBetev** [comment]
� ��� ��� �������

navgeocom.ibnportal.ru
ngc-operational.ibnportal.ru

��� ������� ���������,
��� �� �������� � ��� ������, ���� ��� �����.
������ ������?


Ivan Betev
NAVGEOCOM





From:      
 OlegoO <notifications@github.com>
To:      
 InstantBusinessNetwork/IBN
<IBN@noreply.github.com>
Cc:      
 IvanBetev <ivan.betev@navgeocom.ru>
Date:      
 27.10.2015 15:08
Subject:    
   Re: [IBN] �������
������? (#3)




��� ������� ������ source ��� IBN �������.
����� ����� ��������� ���������� � �����
�������.
—
Reply to this email directly or view
it on GitHub.
