### ISSUE TITLE
Активация.

### ISSUE THREAD

**Issue by RaZLeN** [InstantBusinessNetwork/IBN#5]
Добрый день. Активация не работает стандатрным средстовм, т.к. сервер активации недоступен. Как можно активироваться иначе?

**Comment by OlegoO** [comment]
Используйте Offline активацию.

Serial Number: L65TS-W310C-LD61Y-V4PW3-AER87
License File: https://github.com/InstantBusinessNetwork/IBN/tree/master/Documents/L65TS-W310C-LD61Y-V4PW3-AER87.lic

Сохраните файл лицензии в папку, в которую был установлен IBN Server. Чтобы активировать лицензию, запустите активатор лицензии из папки установки. Для этого введите в командной строке:  
McActivator.exe /i L65TS-W310C-LD61Y-V4PW3-AER87.lic

**Comment by OlegoO** [comment]
https://github.com/InstantBusinessNetwork/IBN#how-to-activate-license
