### ISSUE TITLE
Open Source License

### ISSUE THREAD

**Issue by TumbaumbaZilla** [InstantBusinessNetwork/IBN#9]
Добрый день.
В папке IBN не нашел информацию, что вложено в понятие Open Source License. 
Можете уточнить тип лицензии в соответствии с рекомендацией Github [choosealicense.com](https://choosealicense.com/)?
Есть ли ограничения на использование IBN юридическим лицом
1.  для решения внутренних задач (ведение проектов и инцидентов)? 
2.  для решения внешних задач (ведение инцидентов)?

**Comment by OlegoO** [comment]
нет ограничений использования нет
